const ACRONYMS = [
    'ACDC',
    'AFK',
    'AKA',
    'AMPM',
    'API',
    'ASAP',
    'ASMR',
    'ATM',
    'BAC',
    'BBC',
    'BBQ',
    'BFF',
    'BMW',
    'BMX',
    'BOFA',
    'BRB',
    'BTW',
    'BYOB',
    'CBS',
    'CEO',
    'CGI',
    'CIA',
    'COD',
    'CPU',
    'DAB',
    'DEA',
    'DGAF',
    'DIY',
    'DMV',
    'DNS',
    'DOB',
    'DVD',
    'EDM',
    'ERP',
    'ESPN',
    'ETA',
    'FAQ',
    'FBI',
    'FDA',
    'FIFA',
    'FYI',
    'GDP',
    'GIF',
    'GOAT',
    'GPS',
    'GRE',
    'GTA',
    'HDMI',
    'HDTV',
    'HIV',
    'HOA',
    'ICBM',
    'ICE',
    'IDC',
    'IDGAF',
    'IDK',
    'IHOP',
    'IMO',
    'IPA',
    'IPO',
    'IRS',
    'IYKYN',
    'JFK',
    'JPEG',
    'KFC',
    'LCD',
    'LED',
    'LFG',
    'LLC',
    'LLM',
    'LMAO',
    'LMFAO',
    'LOL',
    'LSAT',
    'LSD',
    'MBA',
    'MDMA',
    'MIA',
    'MILF',
    'MLB',
    'MLK',
    'MMA',
    'MNM',
    'MOAB',
    'MPG',
    'MRI',
    'MSG',
    'MVP',
    'NASA',
    'NBA',
    'NBD',
    'NCAA',
    'NDA',
    'NFT',
    'NPC',
    'NRA',
    'NSA',
    'NSF',
    'OMFG',
    'OMG',
    'OMW',
    'PBR',
    'PCP',
    'PDF',
    'PGA',
    'PMS',
    'POV',
    'PTO',
    'PTSD',
    'RAM',
    'RBI',
    'RIP',
    'ROFL',
    'ROI',
    'RPG',
    'RSVP',
    'SAT',
    'SMH',
    'SNL',
    'SSD',
    'SSN',
    'STD',
    'STFU',
    'TBA',
    'TBH',
    'TBT',
    'THC',
    'TLDR',
    'TMCA',
    'TMI',
    'TMZ',
    'TNT',
    'TSA',
    'TTYL',
    'UFO',
    'URL',
    'USA',
    'USB',
    'USB',
    'USSR',
    'UTI',
    'UTM',
    'VHS',
    'VPN',
    'WIFI',
    'WMBA',
    'WTF',
    'YOLO',
]

const PROMPTS = [
    'Weird name for a company',
    'Funny nickname for someone in the group',
    'Famous last words',
    'Full name of your fictional child',
    'Inappropriate movie title',
    'Funny company slogan',
    'Funny medical conditions',
    'Funny name for the next big seltzer drink',
    'Weird name for an emo punk rock band',
    'Funny bumper sticker',
    'Funny slogan on a shirt',
    'Funny name for this group of people',
    'New sex position',
    'Name for a country you founded',
    'A name that comes up in a sporting event and you have no idea where they are from',
    'Unknown text message from your best friend ',
    'Gen z slang',
    'Worst thing to blurt out at church',
    'New C-suite title',
    'Random charge on your significant others credit card statement',
    'Name for an airline you would not want to fly on',
    'First words in a state of the union address (“my fellow Americans…”)',
    'A name for a piece of art that just makes no sense',
    'Name for a boat',
    'Pick up line',
    'How to ...',
    'Drink if you',
    'I love it when someone',
    'I hate it when someone',
    'Oh my god, is that ...',
    'Weird superpower',
    'A cult that probably exists',
    'Rejected name for a dating app',
    'Thing your ex would name their podcast',
    'The real reason you got fired',
    'Something you’d yell during sex (that ruins the mood)',
    'Weirdest thing you’ve done for money',
    'The title of the autobiography for someone in this group',
    'Company name that definitely launders money',
    'What your group chat would be called if it were a sitcom',
    'Rejected Make-A-Wish request',
    'Something you’d leave in your will to confuse people',
    'What Satan has on his LinkedIn profile',
    'A children’s book that shouldn’t exist',
    'Something you’d find in a wizard’s junk drawer',
    'Rejected Mario Kart power-up',
    'A terrible name for a new cryptocurrency',
    'What your dog thinks you do for a living',
    'An Olympic sport that should be done drunk',
    'The worst thing to whisper into a stranger’s ear',
    'New flavor of Gatorade nobody asked for',
    'The real reason aliens haven’t contacted us',
    'An item you’d bring to a sword fight... that isn’t a sword',
    'A kitchen gadget that actively ruins your food',
    'An invention that solves a problem nobody has',
    'What not to say when you meet your partner’s parents',
    'Awkward way to respond to "I love you"',
    'Worst excuse for calling out of work',
    'A situation that calls for a very slow, very quiet exit',
    'The least useful spell in a wizard’s spellbook',
    'Jedi name for someone in this group',
]

const getRandomIndex = (array) => {
    return Math.floor(Math.random() * array.length)
}

export const getRandomAcronymFromDb = () => {
    return ACRONYMS[getRandomIndex(ACRONYMS)]
}

export const getRandomPromptFromDb = () => {
    return PROMPTS[getRandomIndex(PROMPTS)]
}
